import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="h-[70px] flex items-center justify-between px-32 shadow-md">
          <Link href="/" className="text-2xl text-green-400 font-semibold">
            DIGIARNO
          </Link>
          <div className="flex items-center gap-6 font-bold">
            <Link className="hover:text-green-400" href="/">
              Home
            </Link>
            <Link className="hover:text-green-400" href="/about-us">
              About Us
            </Link>
            <Link className="hover:text-green-400" href="/services">
              Services
            </Link>
            <Link className="hover:text-green-400" href="/blogs">
              Blogs
            </Link>
            <Link className="hover:text-green-400" href="/team">
              Team
            </Link>
            <Link className="hover:text-green-400" href="/contact-us">
              Contact Us
            </Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
